# Render Web Service Configuration
# Production-ready deployment with high availability and auto-scaling

services:
  - type: web
    name: econovault-api
    env: docker
    repo: https://github.com/your-username/econovault-api  # Replace with your repo
    branch: main
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    # High availability configuration
    numInstances: 2  # Minimum 2 instances for HA
    autoDeploy: true
    # Auto-scaling configuration (Professional plan required)
    scaling:
      minInstances: 2
      maxInstances: 10
      targetCPUPercent: 60
      targetMemoryPercent: 65
    healthCheck:
      path: /health
      interval: 30
      timeout: 10
      restartPolicyType: on_failure
      maxRetries: 3
    # Production environment configuration
    envVars:
      # Database Configuration (Render will provide this)
      - key: DATABASE_URL
        fromDatabase:
          name: econovault-db
          property: connectionString
      # Security Keys (generated by Render)
      - key: SECRET_KEY
        generateValue: true
      - key: MASTER_ENCRYPTION_KEY
        generateValue: true
      # API Keys (set via dashboard for security)
      - key: BLS_API_KEY
        sync: false
      - key: BEA_API_KEY
        sync: false
      - key: FRED_API_KEY
        sync: false
      # Application Configuration
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: WAIT_FOR_DB
        value: "true"
      - key: RUN_MIGRATIONS
        value: "true"
      # Production monitoring
      - key: ENABLE_METRICS
        value: "true"
      - key: METRICS_RETENTION_DAYS
        value: "30"
      # Security headers
      - key: SECURE_HEADERS
        value: "true"
      - key: CORS_ORIGINS
        value: "https://econovault.com,https://api.econovault.com"
    # Disk configuration for data persistence
    disk:
      name: econovault-data
      mountPath: /app/data
      sizeGB: 50  # Increased for production data
    # Pre-deploy commands for database migrations
    preDeployCommand: "python -c 'import asyncio; from database import init_db; asyncio.run(init_db())'"

# Database configuration with high availability
databases:
  - name: econovault-db
    databaseName: econovault
    user: econovault_admin
    plan: pro  # Professional plan for HA features
    postgresVersion: "15"
    highAvailability: true  # Enable automatic failover
    backupRetention: 30  # 30-day backup retention

# Environment groups for shared configuration
envGroups:
  - name: econovault-production
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: ENABLE_METRICS
        value: "true"